### PR TITLE
Cleanup tests a little bit

### PR DESCRIPTION
**Pull request by ChihChengLiang**
I'm trying to make writing tests happier. A low hanging fruit is to create more TypeScript interfaces.

Since the Typechain struct doesn't work, we currently manually deconstruct many data structures everywhere. That increased line of code and bad for readability. We should us TypeScript interfaces more in the tests itself and move deconstruction to utils.

In this PR I created the interface of Account and Transaction.

### CODE REVIEW

**Comment by vaibhavchellani** [comment]
Love it! I am very new to JS and typescript and hence didn't venture into this, but this is def the direction we should pursue.

**Comment by vaibhavchellani** [comment]
@ChihChengLiang I would love to merge this, any idea why the CI is failing?

**Comment by ChihChengLiang** [comment]
@vaibhavchellani The CI recently failed at the npm install steps a lot. Usually, I rerun the CI. Can you hit the rerun button for me?

**Comment by vaibhavchellani** [comment]
Sure, done! 

Can you confirm that the `npm run tests` works for you locally?

**Comment by ChihChengLiang** [comment]
Thanks. `npm run tests` works locally for me. But I'm happy to wait for the CI to complete.

**Pull request merged**
