### PR TITLE
Fix github actions

### LINKED ISSUE #35: Fix github actions
github actions job is incorrectly configured at the moment, need to fix it compile and run tests on every push to master.

### PR DESCRIPTION
**Pull request by zemse**
This PR intends to close #35.

Since, running tests requires `npm run ganache` to run in parallel with `npm test`, it seems we need something like [concurrently](https://www.npmjs.com/package/concurrently).

For now, I have just added just the script `npm test` to check if the Github actions success. But more jobs can be added later.

### CODE REVIEW

**Comment by zemse** [comment]
Looks like the `npm run generate` is failing for some reason. @vaibhavchellani can you have a look at the flow? I believe I did the same locally and it worked. But what version of node.js are you using?

**Comment by vaibhavchellani** [comment]
The version for which everything works for me is v10.13 as I have mentioned in the readme. The `npm run generate` runs fine for me.

**Comment by zemse** [comment]
Okay, btw it also worked fine for me.

> Error: Could not find /home/runner/work/contracts/contracts/contracts/Rollup.sol from any sources; imported from /home/runner/work/contracts/contracts/contracts/Deployer.sol

I have a guess that this error has something to do with the fact that the import on [Deployer.sol#L7](https://github.com/Hubble-Project/contracts/blob/master/contracts/Deployer.sol#L7) intends to import `./Rollup.sol`, while the actual file has lower case `r` ([rollup.sol)](https://github.com/Hubble-Project/contracts/blob/master/contracts/rollup.sol)). What do you think? Would you prefer changing the case in the import statement or the file name?

**Comment by zemse** [comment]
I just though this, maybe we can change the OS `ubuntu-latest` as currently in workflow file. Since maybe it worked for us both because probably we are using `macOS`. Though, has anyone tried on `ubuntu-latest`?

**Comment by zemse** [comment]
Though if it works on `macOS` and not on `ubuntu-latest`, I think it still makes sense to instead rename or update import name (whichever is desired), so it'd work on `ubuntu-latest` or other OS too if it didn't.

**Comment by zemse** [comment]
Oh.. after some hiccups, it did work. Let me clean up this mess.

**Comment by zemse** [comment]
I've renamed the imports because I remember that previous I didn't have a good time renaming file names (`name.extension` to `Name.extension` or vv).

**Comment by zemse** [comment]
But if it's needed that the files `rollup.sol` and `logger.sol` to be capitalized, it would be better to be handled in a separate PR.

**Comment by vaibhavchellani** [comment]
Thanks for your contribution. Merging to master 🎉

**Pull request merged**
